---
- name: Copy systemd service
  become: true
  ansible.builtin.template:
    src: templates/prometheus-libvirt-exporter.service.j2
    dest: /lib/systemd/system/prometheus-libvirt-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: Systemctl restart prometheus-libvirt-exporter.service

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
